"""empty message

Revision ID: 029649c9ccb2
Revises: 
Create Date: 2023-07-03 14:40:41.457031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '029649c9ccb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('video_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('video_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('document_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('document_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('image_file_name')
        batch_op.drop_column('image_file_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_file_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('document_data')
        batch_op.drop_column('document_name')
        batch_op.drop_column('video_data')
        batch_op.drop_column('video_name')
        batch_op.drop_column('image_data')
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
